//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagement.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRoomDetail
    {
        public int OrderId { get; set; }
        public int RoomId { get; set; }
        public Nullable<System.DateTime> TimeStart { get; set; }
        public Nullable<System.DateTime> TimeEnd { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual OrderRoom OrderRoom { get; set; }
        public virtual Room Room { get; set; }
    }
}
