//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagement.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTourDetail
    {
        public int OrderId { get; set; }
        public int TourId { get; set; }
        public Nullable<int> QuantityChild { get; set; }
        public Nullable<int> QuantityAdult { get; set; }
    
        public virtual OrderTour OrderTour { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
