//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagement.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Acreage { get; set; }
        public Nullable<int> NumberBed { get; set; }
        public string NoteRoom { get; set; }
        public Nullable<int> HotelId { get; set; }
        public string Image { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
