//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagement.Models.DBContext
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.OrderTourDetails = new HashSet<OrderTourDetail>();
            this.TourDestinations = new HashSet<TourDestination>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<System.DateTime> TimeStart { get; set; }
        public string PositionStart { get; set; }
        public string Transport { get; set; }
        public string Content { get; set; }
        public Nullable<int> QuantityPeople { get; set; }
        public Nullable<decimal> PriceOfChild { get; set; }
        public Nullable<decimal> SurchargeOfRoom { get; set; }
        public Nullable<decimal> PriceOfAdult { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string StopPosition { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Image { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<OrderTourDetail> OrderTourDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<TourDestination> TourDestinations { get; set; }
    }
}
