//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagement.Models.DBContext
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class TourDestination
    {
        public int IdTour { get; set; }
        public int IdDestination { get; set; }
        public string Note { get; set; }

        [JsonIgnore]
        public virtual Destination Destination { get; set; }
        [JsonIgnore]
        public virtual Tour Tour { get; set; }
    }
}
